import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AppProviders } from "@/providers/app-providers";
import "./globals.css";

const googleSans = Roboto({
  variable: "--font-google-sans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${googleSans.variable}`}>
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
